### ISSUE TITLE
Fix rate limit handling after retries are exhausted

### ISSUE THREAD

**Issue by sureshs592** [intercom/intercom-ruby#405] opened 2018-05-28 14:38 UTC
When clients are initialised with `handle_rate_limit = true`, we retry requests automatically when we encounter a rate limit error on [this line](https://github.com/intercom/intercom-ruby/blob/f3448ffe01e934e771ed7af818034330e837e48b/lib/intercom/request.rb#L79).

However, we fail to raise the error if we exhaust all the retries for that request. After 3 retries, the `execute` function will return `nil` for the request. We need to raise the rate limit error after exhausting retries or return a meaningful response.

**Comment by theandrewykim** [comment] 2018-06-04 21:15
@sureshs592 Maybe I'm misunderstanding, but under what circumstances are you able to reproduce this? Right now the behavior of the retry logic should be that the retry should only occur after the the rate limit should be in a 'new window'.

This might indicate that external subsequent requests must be occurring for this failure to occur- so perhaps a different more descriptive error here might be more helpful?

**Comment by sureshs592** [comment] 2018-06-06 20:06
Hey @theandrewykim! Yup we can still hit this issue even after waiting for the new request window (when the limits get reset).

Here's when that can happen:

Say there's some job or integration that has to suddenly perform more than 2000 API calls in a short span of time. Here's what will happen:
- All 2000 calls attempted at once. 500 of them will go through. 1500 will fail and wait for the next request window. (2 retries left)
- Remaining 1500 calls attempted at once. 500 of them will go through. 1000 will fail and wait for the next request window. (1 retry left)
- Remaining 1000 calls attempted at once. 500 of them will go through. 500 will fail. No more retries left at this point. We'll just return `nil` for these 500 calls. This can cause errors upstream in the SDK.

**Comment by choran** [comment] 2018-10-02 08:02
Closing this now since we have merged in the related PR and will do a new release shortly

**Closed by choran** 2018-10-02 08:02 UTC
Labels: bug, in progress, ruby
