### ISSUE TITLE
Memory bloat

### ISSUE THREAD

**Issue by mrhead** [intercom/intercom-ruby#423] opened 2018-09-03 10:35 UTC
`intercom_client.users.find(user_id: 1)` leaks memory on Heroku over time. The weird thing is that I can't reproduce this locally on Mac OS, but I can reproduce it every time on a Heroku dyno.

## Version info
  - intercom-ruby version: 3.5.25
  - Ruby version: 2.5.1

## Expected behavior

RSS memory usage is stable.

## Actual behavior

RSS memory usage is constantly growing over time.

## Steps to reproduce

Run this on a Heroku dyno:

```ruby
loop do
  intercom_client = Intercom::Client.new(token: INTERCOM_API_TOKEN)
  intercom_client.users.find(user_id: 1) # Or any valid user_id
  sleep 1
end
```

I'm going to continue with investigation and hopefully I'll be able to provide more information soon.

**Comment by mrhead** [comment] 2018-09-03 12:01
I did my previous tests with a 521 MB dyno. But now I tried it with a 1 GB dyno again and it looks that memory usage stops growing around 870 MB. So maybe this isn't a memory leak, just a memory bloat.

Our freshly booted Rails process consumes around 260 MB in production. Our web dynos with 20 threads run on 512 MB dynos without any issues. But when I run my test with `intercom_client.users.find(user_id: 1)` in a loop then it consumes 870 MB which is really too much.

I'll post any future findings here.

**Comment by william101** [comment] 2018-09-04 09:06
Hey @mrhead thanks for reporting this issue. 

I've been unable to reproduce this issue with the snippet you posted there. From my analysis, there doesn't appear to be any leak in the client. 

Is there any chance you could provide a bit more information about the leak, possibly a heap dump? You could get a dump with this modified version of your script

```ruby
require 'time'
require 'objspace'

ObjectSpace.trace_object_allocations_start;

stop_at = Time.now + 3600 # 1 hour or long enough

loop do
  intercom_client = Intercom::Client.new(token: INTERCOM_API_TOKEN)
  intercom_client.users.find(user_id: 1) # Or any valid user_id
  sleep 1

  if Time.now.to_i >= stop_at
    GC.start
    File.open("/tmp/intercom-ruby-heap.dump", "w") do |io|
      ObjectSpace.dump_all(output: io)
    end
    break
  end
end
```

Then, analyse the heap dump using [heapy](https://github.com/schneems/heapy/) to see where the extra memory is being allocated in the app.

```
heapy read /tmp/intercom-ruby-heap.dump
```

**Comment by choran** [comment] 2018-10-02 07:27
I will close this for now but if there are any further clarifications on this fell free to re-open or open another issue, whichever is handier.
Thanks

**Closed by choran** 2018-10-02 07:27 UTC
Labels: question, ruby
