### ISSUE TITLE
NoMethodError: undefined method post for nil:NilClass when adding a tag

### ISSUE THREAD

**Issue by davetron5000** [intercom/intercom-ruby#514] opened 2020-02-25 14:02 UTC
## Version info
  - intercom-ruby version: 4.0.0
  - Ruby version: 2.7.0

## Expected behavior

Calling `add_tag` would not throw an exception about the  `post` method not being found on `NilClass`

## Actual behavior

An exception is thrown sometimes.  I cannot tell the conditions under which this happens, but it could be due to rate limiting not being handled?  That's just a guess.  See below for more details.

## Steps to reproduce

The process I have implemented is to  bulk create/update users in my system with Intercom.  Initially I did this as fast as possible and got rate-limited.  Now, I space our the jobs to avoid rate-limiting, and have configured them to retry.

This process does work, and everything does sync.  The problem I'm seeing here is coming from the internals of the intercom gem *sometimes*, and for the given record that generates it, retries eventually succeed.

Thus, my guess is that there's some sort of rate limiting happening when I call `add_tag` that is not handled.  The internals of this gem are highly abstracted and I can't really follow how it works otherwise I'd try to be more helpful.

Anyway, more details:

This happens when I create a contact.  When I create a contact, right after I add a tag to them to indicate that my app was the creator of the record.  The tag exists and succeeds most of the time.  In fact, after retrying the Sidekiq job that manages this, the calls eventually do succeed.

Here is what the code mostly looks like:

```ruby
    intercom_contact_from_api = intercom_client.contacts.create(
        role: "user",
        external_id: intercom_contact.id.to_s,
        email: intercom_contact.email,
        phone: intercom_contact.phone,
        name: intercom_contact.name,
        last_seen_at: intercom_contact.last_seen_at.utc.to_i,
        signed_up_at: intercom_contact.signed_up_at.utc.to_i,
        custom_attributes: coerce_custom_attribute_values_types(intercom_contact.custom_fields),
    )
    intercom_tag = intercom_client.tags.find(name: "imported_from_my_app")
    if intercom_tag.present?
      intercom_contact_from_api.add_tag(id: intercom_tag.id)
    else
      raise
      log :create_contact, "Could not find 'imported_from_my_app' tag in Intercom, so cannot tag IntercomContact #{intercom_contact.id} with it"
    end
```

## Logs

Unfortunately, Bugsnag and Sidekiq hate real stack traces so I don't have the full trace into the intercom API client, but I do have the line where it happens:

```
NoMethodError: undefined method `post' for nil:NilClass
WARN: /app/vendor/bundle/ruby/2.7.0/gems/intercom-4.0.0/lib/intercom/api_operations/nested_resource.rb:37:in `block (2 levels) in nested_resource_methods'
```

**Comment by murtron** [comment] 2020-03-10 10:46
Looks like the same root cause as https://github.com/intercom/intercom-ruby/issues/513 which is fixed in the latest release, 4.0.1. Sorry about the trouble @davetron5000 and thanks for the detailed report!

Any further issues, feel free to reopen.

**Closed by murtron** 2020-03-10 10:46 UTC
