### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by heaven** [intercom/intercom-ruby#344] opened 2017-06-19 08:57 UTC
Noticed this error in Airbrake:
https://github.com/intercom/intercom-ruby/blob/master/lib/intercom/request.rb#L94

Either due to a network failure or the service returned a wrong response. 

Backtrace:
```
/gems/intercom-3.5.12/lib/intercom/request.rb:94 in parse_body
/gems/intercom-3.5.12/lib/intercom/request.rb:70 in block in execute
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:853 in start
/gems/intercom-3.5.12/lib/intercom/request.rb:65 in execute
/gems/intercom-3.5.12/lib/intercom/client.rb:111 in execute_request
/gems/intercom-3.5.12/lib/intercom/client.rb:92 in post
/gems/intercom-3.5.12/lib/intercom/api_operations/save.rb:27 in save
/gems/intercom-3.5.12/lib/intercom/api_operations/save.rb:19 in create
app/workers/worker/intercom_event_logger.rb:19 in process
app/workers/worker/base.rb:31 in block in perform
```

**Comment by choran** [comment] 2017-08-17 10:53
Hi @heaven,
What was the actual cause of the error, like you said, was it a network failure? I was just wondering what you were attempting at the time? i.e. can you provide some steps so I can reproduce it and see why it is returning the wrong error

**Comment by heaven** [comment] 2017-08-17 11:05
Hi, can't tell for sure, we have a worker that sends events to Intercom, these jobs being processed by Sidekiq and sometimes they fail with that error. Seems like this line `parsed_body = JSON.parse(decoded_body)` produced nil, not raised parse error, and also passed this check `return parsed_body if decoded_body.nil? || decoded_body.strip.empty?`. Can't imagine how should that string look like :)

**Comment by choran** [comment] 2017-08-21 12:38
Yeah, that is strange, like you said I cant see how it could be empty with the nil and empty check in return parsed_body if decoded_body.nil? || decoded_body.strip.empty?. Not sure what extra check is needed there.
At the moment I am not able to reproduce this myself. 
I am wondering is it to do with the message_for_unexpected_error_without_type? That should catch all the errors and has a fall through for an unexpected error. Assuming it wasnt a parsed error

**Comment by choran** [comment] 2017-09-07 15:23
Hi @heaven 
I think I see the issue here, it looks to be same as noted here #339 
So I will close this issue and track it under that one. 
Thanks
Cathal

**Closed by choran** 2017-09-07 15:23 UTC
