### ISSUE TITLE
Companies do not update when modifying user.companies object

### ISSUE THREAD

**Issue by thewheat** [intercom/intercom-ruby#368] opened 2017-11-24 04:57 UTC
Updating the companies object on a user and saving the user does not currently update the company.
```
user = @intercom.users.find(user_id: "1")
user.name = "Update via API"
user.companies.first.name = "Co name via API" 
intercom.users.save(user)
# company name will not be saved
```

You currently have to assign a new array on the company to get it to update
```
user = @intercom.users.find(user_id: "1")
user.name = "Update via API"
user.companies= [{"company_id": THE_COMPANY_ID, "name": "Co name via API"}] 
intercom.users.save(user)
# company name will be saved
```

## Version info
  - intercom-ruby version: `3.5.22`
  - Ruby version: `ruby 2.3.1p112`

## Expected behavior
Company to be updated

## Actual behavior
Company not updated

## Steps to reproduce
 1. Run code similar to the following
```
user = @intercom.users.find(user_id: "1")
user.name = "Update via API"
user.companies.first.name = "Co name via API"
intercom.users.save(user)
```

**Comment by P9GIT** [comment] 2017-11-27 08:33
@thewheat 

I'm suspecting this might be similar to my experience here: https://github.com/intercom/intercom-ruby/issues/367

By assigning a new array you implicitly remove the "type" parameter which is not allowed by the API when updating a company object.

Hope this helps.

Thomas.

**Comment by thewheat** [comment] 2017-11-27 08:52
Interesting @P9GIT! I do think there is indeed some overlap here. 

Ideally I think we should get the SDK in a state where we shouldn't have to worry about little nuances like this and have it all handled automatically 😄

**Comment by choran** [comment] 2017-11-27 12:01
@thewheat @P9GIT I am not sure it is related to the type issue, I think it is likely due to the way use [Flatstore](https://github.com/intercom/intercom-ruby/blob/7b67fc04b181319b4cef6eb23b2442135408e986/lib/intercom/lib/flat_store.rb).
So it is not specific to companies. It is just that companies are a list of objects. 
We treat users like a flatstore so when you assign a new array it will be detected and updated as part of user and will work as described.
However, when you update a companies object in the list then the flatstore does not know something has changed since it does not iterate through the companies on the list.
This was not an oversight, it was designed this way, I think there was a fear of checking for nesting and possible hitting an infinite looping issue if the next level object had another nested datatype and so on.
For my two cents, this is not something we should prioritize, the effort to do this will yield very little value since there is a recommended way to update companies. We should instead focus on other ares of the SDK where there are is functionality missing from the API.
So I am inclined to close this issue but I will leave it open for now for other peoples 'two cents' 👍

**Comment by hahmed** [comment] 2018-01-26 11:44
@choran 

> We should instead focus on other ares of the SDK where there are is functionality missing from the API.

Would love to contribute, any areas in particular I can work on to get the api on par with the SDK?

**Comment by choran** [comment] 2018-02-07 09:35
@hahmed thanks for your interest. One thing to look for is if people open issues here, that can be a good place to start if you want to make changes to the SDK.
Alternatively if you would like to add a new feature you could look at the API reference and see where you think functionality is missing.
As an example, something I noticed recently is that I dont think we all listing of all conversations by default (noted in the API [here](https://developers.intercom.com/v2.0/reference#section-all-conversations)). Instead we allow you to list them via admin or users but or open but not just an empty list like we describe in the API. That might be a good place to start.
Outside of that I think we need to add support for group related conversations actions and snoozing (API ref [here](https://developers.intercom.com/v2.0/reference#adding-to-group-conversations-as-customer)). These were new features added that we have not added to the SDK yet
Again, thanks for the interest, I will close this issue that was opened here, I left it open initially to see if there was any feedback on this companies issue. We can always reopen this issue if people feel that this is a needed feature.

**Closed by choran** 2018-02-07 09:35 UTC
