### ISSUE TITLE
Missing company custom_attributes

### ISSUE THREAD

**Issue by JIucToyxuu** [intercom/intercom-ruby#279] opened 2016-08-23 09:00 UTC
## Version info
- intercom-ruby version: 3.5.2
- Ruby version: 2.1.2
## Expected behavior

  Each company given via user.companies relation should have custom_attributes of company.
## Actual behavior

   Companies given via user relation have empty custom_attributes. But if get company via search - then custom_attributes contain correct values.
## Steps to reproduce
1. intercom_client = Intercom::Client.new(app_id: 'MY_ID', api_key: '****')
2. intercom_user = intercom_client.users.find(user_id: 'fake_user_id')
3. intercom_company = intercom_user.companies.first
4. intercom_company.custom_attributes # is empty hash
5. company = intercom_client.companies.find(company_id: intercom_company.company_id)
6. company.custom_attributes # is not empty and contain correct values

**Comment by choran** [comment] 2017-08-15 16:17
Thanks for raising this and sorry for the delay in getting back. I think this is expected behaviour since when you retrieve a user via the API itself you will only get a list of companies with name, id and company_id. So we do not return the full company object via the user. It is just to show what companies are associated with the user. 
I agree it is confusing to return the custom_attributes part since it is never populated via the API so would never be populated here either. So one change would be to possibly see if we could remove that but it will not be possible to populate the full company object when you search via a user.
I will close this now but if you feel I missed anything please feel free to re-open

**Closed by choran** 2017-08-15 16:17 UTC
