### ISSUE TITLE
Unable to retrieve archived contacts to unarchive them

### ISSUE THREAD

**Issue by atcruice** [intercom/intercom-ruby#561] opened 2020-11-05 02:26 UTC
This gem recently gained the ability to archive and unarchive contacts, #551. I'm unable to retrieve an archived contact to unarchive them. Is this expected behaviour?

## Version info
  - intercom-ruby version: 4.1.2
  - Ruby version: 2.6.6

## Expected behavior
```ruby
# at least
intercom.contacts.find(id: archived_contact_id) # => an Intercom::Contact

# maybe
intercom.contacts.search(query: {field: "id", operator: "=", value: archived_contact_id}).first # => an Intercom::Contact
intercom.contacts.search(query: {field: "email", operator: "=", value: archived_contact_email}).first # => an Intercom::Contact
```

## Actual behavior
```ruby
intercom.contacts.find(id: archived_contact_id) # => Intercom::ResourceNotFound exception
intercom.contacts.search(query: {field: "id", operator: "=", value: archived_contact_id}).first # => nil
intercom.contacts.search(query: {field: "email", operator: "=", value: archived_contact_email}).first # => nil
```

## Steps to reproduce
 1. manually archive a contact via the Intercom web UI (noting their ID and email)
 2. wait a few minutes for eventual consistency
 3. using an `Intercom::Client` configured for the same workspace, try and retrieve the archived contact using any method listed above

## Other things I tried
```ruby
# this works ✅
contact = Intercom::Contact.new(id: archived_contact_id)
intercom.contacts.unarchive(contact)
# note that obtaining archived_contact_id requires either:
# - already having the complete contact object some other way
# - parsing the ID out of an Intercom::MultipleMatchingUsersError exception message
```
```ruby
# this doesn't ❌
contact = Intercom::Contact.new(email: archived_contact_email)
intercom.contacts.unarchive(contact) # => Intercom::ResourceNotFound exception
```

**Comment by theandrewykim** [comment] 2021-09-20 20:03
This is currently expected behavior of our API at the moment. Marked as a feature and closing for now.

**Closed by theandrewykim** 2021-09-20 20:03 UTC
Labels: feature, wontfix

**Comment by macdonaldr93** [comment] 2021-12-18 16:50
How are we supposed to unarchive a user? I have an app where users can reinstall and I'd like to unarchive their old account

**Comment by drakedeatonuk** [comment] 2023-02-23 15:14
This is a mind blowingly stupid short-sight.

Via API, you need a user's ID to unarchive them... but when you search for the user the API returns null... because they user is archived... So how exactly are you supposed to find an archived user and unarchive them?
